sudo: required
services:
  - docker
  - postgresql
  - redis-server

before_install: 
  - psql -c 'CREATE TABLE values (number INTEGER);' -U postgres
  - psql -c "ALTER USER postgres PASSWORD '1234';" -U postgres
  - docker build -f ./api/Dockerfile -t kwangduck/docker-fibonacci-complex-api-test ./api
      

script:
  - docker run -e CI=true kwangduck/docker-fibonacci-complex-react-test npm run test
  - docker run kwangduck/docker-fibonacci-complex-api-test

language: generic
