sudo: required
services:
  - docker
  - postgresql
  - redis-server

before_install: 
  - psql -c 'CREATE TABLE IF NOT EXISTS values (number INTEGER);' -U postgres
  - psql -c "ALTER USER postgres PASSWORD '1234';" -U postgres
  - redis-cli HSET values 5 8
  - docker pull kwangdock/docker-fibonacci-complex-api-dev 
  - docker pull kwangdock/docker-fibonacci-complex-web-dev 
      
script:
  - docker run --network=host -t -v /app/node_modules -v ./api:/app kwangdock/docker-fibonacci-complex-api-dev npm run test &&
    docker run -e CI=true -t -v /app/node_modules -v ./web:/app kwangdock/docker-fibonacci-complex-web-dev npm run test

language: generic
