sudo: required
services:
  - docker

before_install: 
  - docker build -f ./web/Dockerfile.dev -t kwangduck/docker-fibonacci-complex-react-test ./web
  - docker build -e POSTGRES_USER=postgres POSTGRES_PASSWORD=1234 POSTGRES_DB=postgres postgres:14
  - docker build redis:7  
      

script:
  - docker run -e CI=true kwangduck/docker-fibonacci-complex-react-test npm run test

language: generic
