sudo: required
services:
  - docker

before_install: 
  - docker build -f ./web/Dockerfile.dev -t kwangduck/docker-fibonacci-complex-react-test ./web
  - docker run -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=1234 -e POSTGRES_DB=postgres postgres:14
  - docker run redis:7  
      

script:
  - docker run -e CI=true kwangduck/docker-fibonacci-complex-react-test npm run test

language: generic
