sudo: required
services:
  - docker
  - postgresql
  - redis-server

before_install: 
  - psql -c 'CREATE TABLE values (number INTEGER);' -U postgres
  - psql -c "ALTER USER postgres PASSWORD '1234';" -U postgres
  - redis-cli "HSET values 5 8"
  - docker build -f ./api/Dockerfile.dev -t kwangduck/docker-fibonacci-complex-api-test ./api
      

script:
  - docker run --network=host kwangduck/docker-fibonacci-complex-api-test npm run test

language: generic
