sudo: required
services:
  - docker
  - postgresql
  - redis-server

before_install: 
  - psql -c 'CREATE TABLE values (number INTEGER);' -U postgres
  - psql -c "ALTER USER postgres PASSWORD '1234';" -U postgres
  - redis-cli HSET values 5 8
  - docker pull kwangdock/docker-fibonacci-complex-api-dev 
      
script:
  - docker run --network=host kwangdock/docker-fibonacci-complex-api-dev npm run test

language: generic
