services:
  nginx:
    container_name: nginx
    image: kwangdock/docker-fibonacci-complex-nginx
    restart: always
    depends_on:
      - web
      - api
    ports:
      - 80:80
  api:
    container_name: api
    image: kwangdock/docker-fibonacci-complex-api
    depends_on:
      - postgres
      - redis
    expose:
      - 5000
    environment:
      - REDIS_URL=redis://redis
      - PSQL_URL=postgresql://postgres:1234@postgres:5432/postgres
  worker:
    container_name: worker
    image: kwangdock/docker-fibonacci-complex-worker
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis
  web:
    container_name: web
    image: kwangdock/docker-fibonacci-complex-web
    expose:
      - 3000
