services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    expose: 
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
  redis:
    container_name: redis
    image: redis:7
    restart: always
    expose:
      - 6379
  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis
      - PSQL_URL=postgresql://postgres:1234@postgres:5432/postgres
  worker:
    container_name: worker
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_URL=redis://redis

